### ISSUE TITLE
Feature request: different images

### ISSUE THREAD

**Issue by nonumber** [perceptron8/pinky#1]
Would be nice to be able to select a more prominent image instead of the Magenta.png. For example an animated gif like:
http://rs254.pbsrc.com/albums/hh119/Michael_Hogue/Animated%20GIF%20Library/Animated%20Dividers/dividers_1369.gif~c100

**Comment by perceptron8** [comment]
It would be nice, but it is, sadly, impossible. At least partially, at least now.

1. only the first frame of .gif is being shown by game engine; actual TSO people/buildings animations are stored as sprites, so it seems they must be handled explicitly,

2. flash plugin doesn't "understand" redirects to web_accessible_resources OR chrome doesn't handle redirects to web_accessible_resources if they are made by flash plugin (see https://code.google.com/p/chromium/issues/detail?id=345160 and https://code.google.com/p/chromium/issues/detail?id=484016, star them if you like),

3. it's impossible to redirect to blob: urls in background script (see https://code.google.com/p/chromium/issues/detail?id=397147 and https://code.google.com/p/chromium/issues/detail?id=446453, star them if you like).

When 2 is fixed, I'll be able to give you more colors to choose.
When 2 and 3 is fixed, I'll be able to implement redirection to anything* (single colors, gradients, user uploaded images), apply some graphic filters on the original collections and so on...

* excluding animations

Thank you for reporting, there's still hope :-)

**Comment by nonumber** [comment]
I don't mind if it won't work with external images. Just one or 2 more colors/images to choose from.
So they could easily be stored in the plugin folder like the magenta.png.

So animated gifs are not possible, that's a shame.

Maybe this is an idea, but maybe too heavy on the script/rendering.
Make it flip between 3 images every .2 seconds or so.
So then you can have a Cyan, Magenta and Yellow png and the collectables would look like they 'flicker'.

**Comment by nonumber** [comment]
PS: real nice job you did with this plugin, btw :)

**Comment by perceptron8** [comment]
"web_accessible_resources" are actually the ones within plugin folder. Currently can't use any of them because of issues mentioned in 2. I'm waiting for fixes. Right now, as you can see in code, redirection is made to http://upload.wikimedia.org/wikipedia/commons/f/f1/Magenta.png, not internal magenta.png (otherwise flash plugin won't handle redirection). Wikimedia seems to be reliable source for now - hope they won't change this image to something inappropriate ;)

Thanks for suggestion! Unfortunately, your idea won't work. Even if I modify response headers causing image not to be cached by the browser, it's still cached by TSO app. Only one request is made, only when the image is needed. You have to relog if you wan't it to be refreshed.

If one day extensions could edit request/response body - see https://code.google.com/p/chromium/issues/detail?id=91191 and https://code.google.com/p/chromium/issues/detail?id=104058, that's another ones! :) - I hope to implement "self-collecting". Everything depends on chromium guys and their's security policies. It is possible now, but It's far too complicated (chrome app as a proxy + chrome ext as controller).

I'm glad that you like my plugin and hope it serves you well :)

**Comment by nonumber** [comment]
Ah, ok, sorry for misunderstanding :)

**Comment by perceptron8** [comment]
Something can be done!
http://www.w3schools.com/tags/ref_colorpicker.asp +
http://dummyimage.com/128x128/ff00ff/ff00ff.png (e.g.)
Although it would be just another solid color, it's better than nothing. Interested?

**Comment by nonumber** [comment]
Could be nice.
Idea was however to have it animated, so it stands out more.

**Comment by perceptron8** [comment]
Well... It won't be more visible, I checked many colors / patterns. Pink is beyond compare, hence the silly extension's name. Ability to change color won't add much value, but will make code more complicated. I want it to stay simple. Closing for now.

**Comment by nonumber** [comment]
I understand and agree :)
